Homework is done...
mikutsky/html-2-HW pull request #1
Opened 2020-01-19 06:50 UTC by mikutsky

Сделал все по макету, от сюда: [https://www.figma.com/file/yklifRuRdBND4k6wlA7So0/Easy-Code](url)
С помощью PerfectPixel все подогнал, кроме верхнего меню - там оно не аккуратно отцентрованно в макете.

2020-01-20 01:50 UTC, soulr1ver requested changes

2020-01-20 01:50 UTC, soulr1ver commented on index.html
> +        <div class="inner bg-clouds">
всё гуд! единственное, в этом моменте можешь убрать этот див, а перекинуть его классы в секцию. ведь в данном случае секция не несёт никакой нагрузки, поэтому она является сейчас лишним элементом. если ты понимаешь, что ты можешь сделать что-то, используя меньше элементов - делай так. количество узлов в доме влияет на производительность и на сео в том числе

2020-01-20 10:59 UTC, mikutsky commented on index.html
> +        <div class="inner bg-clouds">
Спасибо! Это вопрос меня теже посетил, когда писал. Сейчас поправлю.

2020-01-27 09:31 UTC, soulr1ver approved these changes

2020-01-27 09:31 UTC, merged